version: "3.8"

services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    volumes:
      - crowdsec-config:/etc/crowdsec
      - crowdsec-db:/var/lib/crowdsec/data
      - /var/log:/var/log:ro
    ports:
      - "8080:8080"  # LAPI interne
    environment:
      - TZ=Europe/Paris

  bouncer-firewall:
    image: crowdsecurity/crowdsec-firewall-bouncer:latest
    container_name: cs-firewall-bouncer
    network_mode: "host"
    restart: unless-stopped
    environment:
      - CROWDSEC_LAPI_URL=http://localhost:8080/
      - CROWDSEC_LAPI_KEY=${CROWDSEC_LAPI_KEY}
    volumes:
      - crowdsec-config:/etc/crowdsec:ro
    cap_add:
      - NET_ADMIN

  console:
    image: ghcr.io/crowdsecurity/crowdsec-console:latest
    container_name: crowdsec-console
    ports:
      - "8081:8080"
    environment:
      - LAPI_URL=http://crowdsec:8080/
      - LAPI_USERNAME=admin
      - LAPI_PASSWORD=${CONSOLE_PASSWORD}
      - LAPI_SKIP_VERIFY=true
    restart: unless-stopped

volumes:
  crowdsec-config:
  crowdsec-db:
